/**
 * Second batch of enterprise feedback personas — spread into `customerFeedbackReviews` in data.ts.
 * This batch: 41 Positive, 23 Mixed, 6 Critical (~57% / ~33% / ~10% combined with batch 1).
 */
export const additionalEnterpriseFeedbackReviews = [
  {
    id: 'fb-ext-camille-rousseau',
    name: 'Camille Rousseau',
    role: 'Retail Operations Director',
    companyContext: 'France · Specialty apparel · 2,400 stores',
    rating: 4.5,
    sentiment: 'Positive' as const,
    category: 'Value Delivered' as const,
    review:
      'Store leads use one narrative on shrinkage, returns assistance, and staffing—finally aligned with what HQ sees in the agent console.',
    likes: 'Cross-team vocabulary that survives a monthly ops review.',
    improves: 'Simpler drill paths for district managers on mobile.',
  },
  {
    id: 'fb-ext-wei-zhang',
    name: 'Wei Zhang',
    role: 'Healthcare Compliance Manager',
    companyContext: 'Singapore · Integrated health system · 18 hospitals',
    rating: 3.5,
    sentiment: 'Mixed' as const,
    category: 'Governance' as const,
    review:
      'Policy mapping is thoughtful, but we still bridge two weeks of manual evidence gathering before committee sign-off.',
    likes: 'Clear ownership labels on workflow steps.',
    improves: 'Packaged control matrices we can drop into our GRC tool without re-keying.',
  },
  {
    id: 'fb-ext-alma-vukovic',
    name: 'Alma Vuković',
    role: 'Enterprise Architect',
    companyContext: 'Croatia · Regional telecom · Enterprise IT',
    rating: 4.5,
    sentiment: 'Positive' as const,
    category: 'Operational Health' as const,
    review:
      'Reference architecture views helped us argue for a single observability path instead of five bespoke monitors.',
    likes: 'Honest about integration maturity; fewer surprises in security review.',
    improves: 'Architecture decision records exportable as Markdown for our internal wiki.',
  },
  {
    id: 'fb-ext-tyrell-banks',
    name: 'Tyrell Banks',
    role: 'Contact Center Supervisor',
    companyContext: 'US Southeast · Insurance claims · 900 seats',
    rating: 4,
    sentiment: 'Mixed' as const,
    category: 'Value Delivered' as const,
    review:
      'Coaching dashboards help, but onboarding non-technical team leads took longer than promised—too many knobs before the first win.',
    likes: 'Agent-level quality signals my coaches can act on same day.',
    improves: 'Guided “first 30 days” templates with fewer empty states.',
  },
  {
    id: 'fb-ext-ingrid-soderlund',
    name: 'Ingrid Söderlund',
    role: 'AI Transformation Lead',
    companyContext: 'Sweden · Industrial OEM · Digital office',
    rating: 5,
    sentiment: 'Positive' as const,
    category: 'Value Delivered' as const,
    review:
      'Executive reporting finally shows adoption and risk in one place; the board asked fewer one-off dig requests this quarter.',
    likes: 'Credible pacing narrative for a conservative engineering culture.',
    improves: 'Stronger benchmarks vs. peer manufacturing verticals (even anonymized).',
  },
  {
    id: 'fb-ext-rohit-kapoor',
    name: 'Rohit Kapoor',
    role: 'Solutions Consultant',
    companyContext: 'India · IT services · Pre-sales COE',
    rating: 4,
    sentiment: 'Positive' as const,
    category: 'Agent Effectiveness & Trust' as const,
    review:
      'Demo depth is there when prospects push on human-in-the-loop workflows—we can show corrections without a custom lab build.',
    likes: 'Trust surfaces that survive technical due diligence.',
    improves: 'Faster sandbox reset between customer workshops.',
  },
  {
    id: 'fb-ext-melissa-cho',
    name: 'Melissa Cho',
    role: 'Fraud Operations Analyst',
    companyContext: 'Canada · Digital bank · Fraud center',
    rating: 3.5,
    sentiment: 'Mixed' as const,
    category: 'Agent Effectiveness & Trust' as const,
    review:
      'Trust scoring still feels too abstract for investigators—we need the model to show why a case ranked “high” beyond a composite index.',
    likes: 'Good linkage between alerts and agent-assisted summaries.',
    improves: 'Feature attributions we can paste into case narratives.',
  },
  {
    id: 'fb-ext-giancarlo-ferri',
    name: 'Giancarlo Ferri',
    role: 'IT Governance Lead',
    companyContext: 'Italy · Multi-brand luxury group',
    rating: 3,
    sentiment: 'Critical' as const,
    category: 'Governance' as const,
    review:
      'Would require stronger audit trails before rollout: who toggled a policy, when, and what downstream agents inherited the change.',
    likes: 'The product clearly wants to speak “controls language.”',
    improves: 'Immutable event log with tenant-scoped retention policies.',
  },
  {
    id: 'fb-ext-yasmin-el-amin',
    name: 'Yasmin El-Amin',
    role: 'Security Operations Manager',
    companyContext: 'UAE · Enterprise marketplace · Trust & safety',
    rating: 4,
    sentiment: 'Mixed' as const,
    category: 'Operational Health' as const,
    review:
      'Operational metrics are excellent; dependency monitoring still buries a few third-party auth failures until we customize alerts.',
    likes: 'Incident timelines that don’t assume you live in kubectl.',
    improves: 'Lower default alert noise for tier-1 rotations.',
  },
  {
    id: 'fb-ext-peter-macallan',
    name: 'Peter MacAllan',
    role: 'Head of Digital Transformation',
    companyContext: 'Scotland · Utilities · Customer operations',
    rating: 4.5,
    sentiment: 'Positive' as const,
    category: 'Value Delivered' as const,
    review:
      'Cross-team alignment improved between field service and the digital assistant owners—fewer “not my metric” debates.',
    likes: 'Shared definitions for resolution and containment.',
    improves: 'Offline-first read-only packs for technicians in low-connectivity zones.',
  },
  {
    id: 'fb-ext-lena-wojcik',
    name: 'Lena Wójcik',
    role: 'Knowledge Base Administrator',
    companyContext: 'Poland · B2B SaaS · Support knowledge',
    rating: 3.5,
    sentiment: 'Mixed' as const,
    category: 'Agent Effectiveness & Trust' as const,
    review:
      'Discoverability of which articles the agent prioritized is better, but reconciliation when Confluence and the CMS disagree is still manual.',
    likes: 'Visible drift between published policy and agent behavior.',
    improves: 'Bulk diff when source pages move or are archived.',
  },
  {
    id: 'fb-ext-caleb-morrison',
    name: 'Caleb Morrison',
    role: 'CRM Operations Manager',
    companyContext: 'US Midwest · MedTech commercial · Salesforce org',
    rating: 4.5,
    sentiment: 'Positive' as const,
    category: 'Value Delivered' as const,
    review:
      'RevOps and CS stopped exporting five CSVs to explain the same quarter. Agent quality now sits beside pipeline hygiene in QBRs.',
    likes: 'Executive reporting that respects CRM object reality.',
    improves: 'Native Salesforce Lightning cards for two KPIs we care about weekly.',
  },
  {
    id: 'fb-ext-anika-desai',
    name: 'Anika Desai',
    role: 'Technical Support Lead',
    companyContext: 'Ireland · Enterprise networking vendor · TAC',
    rating: 5,
    sentiment: 'Positive' as const,
    category: 'Operational Health' as const,
    review:
      'Latency visibility across regions made our escalation story honest with marquee accounts.',
    likes: 'Provider reliability summarized without vendor cheerleading.',
    improves: 'Ticket mirror into ServiceNow with stable field mapping.',
  },
  {
    id: 'fb-ext-henrik-johansen',
    name: 'Henrik Johansen',
    role: 'Enterprise Procurement Manager',
    companyContext: 'Norway · Logistics conglomerate · Indirect procurement',
    rating: 3.5,
    sentiment: 'Mixed' as const,
    category: 'Cost Optimization' as const,
    review:
      'Procurement evaluation packs helped, but contract caps and true-up math needed finance to rebuild the model anyway.',
    likes: 'Transparent unit economics narrative for steering committees.',
    improves: 'Editable assumption worksheets with version history.',
  },
  {
    id: 'fb-ext-soraya-mensah',
    name: 'Soraya Mensah',
    role: 'Data Governance Specialist',
    companyContext: 'Ghana · Pan-African bank · Data office',
    rating: 4,
    sentiment: 'Mixed' as const,
    category: 'Governance' as const,
    review:
      'Lineage hints are useful prototypes; scaling concerns remain when we federate across three data meshes.',
    likes: 'Plain-language stewardship labels.',
    improves: 'Stronger connectors for catalog APIs we already pay for.',
  },
  {
    id: 'fb-ext-tomasz-nowicki',
    name: 'Tomasz Nowicki',
    role: 'Customer Retention Manager',
    companyContext: 'Poland · Subscription fitness · Growth',
    rating: 4.5,
    sentiment: 'Positive' as const,
    category: 'Value Delivered' as const,
    review:
      'Churn drivers tied to assistant failures are finally visible—product took two items into sprint without a fight.',
    likes: 'Honest segmentation; doesn’t hide ugly cohorts.',
    improves: 'Experiment hooks to measure retention lift after prompt changes.',
  },
  {
    id: 'fb-ext-fiona-mactavish',
    name: 'Fiona MacTavish',
    role: 'Global Support Director',
    companyContext: 'UK · Fintech scale-up · EMEA + Americas',
    rating: 5,
    sentiment: 'Positive' as const,
    category: 'Value Delivered' as const,
    review:
      'Rollout readiness reviews are shorter because accountability for model changes is obvious in the UI.',
    likes: 'Operational accountability without a separate RACI spreadsheet.',
    improves: 'Time-zone aware executive snapshots.',
  },
  {
    id: 'fb-ext-javier-castillo',
    name: 'Javier Castillo',
    role: 'Workforce Planning Lead',
    companyContext: 'Mexico · Telecom retail · Workforce mgmt',
    rating: 3.5,
    sentiment: 'Mixed' as const,
    category: 'Value Delivered' as const,
    review:
      'Forecasting impact on handle time is plausible, but we need clearer assumptions when seasonality spikes.',
    likes: 'Bridges WFM conversations with qualitative quality data.',
    improves: 'Exportable scenarios HRIS can ingest.',
  },
  {
    id: 'fb-ext-adepero-adeyemi',
    name: 'Adepero Adeyemi',
    role: 'Service Delivery Manager',
    companyContext: 'Nigeria · Enterprise IT outsourcing · Managed services',
    rating: 4.5,
    sentiment: 'Positive' as const,
    category: 'Operational Health' as const,
    review:
      'SLA storytelling improved for clients who ask about AI-assisted tickets—one pane for latency and backlog risk.',
    likes: 'Service delivery language, not just ML jargon.',
    improves: 'Client-safe PDF summaries with redaction rules.',
  },
  {
    id: 'fb-ext-helen-ostrander',
    name: 'Helen Ostrander',
    role: 'Internal Audit Manager',
    companyContext: 'US · Mutual insurance · Second line',
    rating: 2.5,
    sentiment: 'Critical' as const,
    category: 'Governance' as const,
    review:
      'Promising direction, yet auditability stops short of what our external auditors expect—sample selection still manual.',
    likes: 'The team understands evidence trails matter.',
    improves: 'Sampling workflows with signed exports and hash manifests.',
  },
  {
    id: 'fb-ext-samira-hakim',
    name: 'Samira Hakim',
    role: 'AI Ethics Advisor',
    companyContext: 'Netherlands · Retail banking · Responsible AI',
    rating: 4,
    sentiment: 'Mixed' as const,
    category: 'Governance' as const,
    review:
      'Ethics review boards get clearer narratives, but confidence calibration for edge demographics still needs external validation hooks.',
    likes: 'Documentation tone is cautious and specific.',
    improves: 'Structured bias incident logging with closure criteria.',
  },
  {
    id: 'fb-ext-brett-sullivan',
    name: 'Brett Sullivan',
    role: 'Senior Product Strategist',
    companyContext: 'Australia · Workplace SaaS · Portfolio office',
    rating: 4.5,
    sentiment: 'Positive' as const,
    category: 'Value Delivered' as const,
    review:
      'Portfolio reviews gained a spine: which bets are learning, which are burning support load.',
    likes: 'Connects product outcomes to operational load.',
    improves: 'Roadmap tagging so initiatives map to agent families.',
  },
  {
    id: 'fb-ext-mei-ling-chan',
    name: 'Mei-Ling Chan',
    role: 'Marketplace Quality Lead',
    companyContext: 'Hong Kong · Regional marketplace · Buyer trust',
    rating: 4,
    sentiment: 'Positive' as const,
    category: 'Agent Effectiveness & Trust' as const,
    review:
      'Seller-facing assistant quality is measurable now; we escalated two policy gaps with data instead of anecdotes.',
    likes: 'Human review queues that don’t fight our moderation tools.',
    improves: 'Locale-specific rubrics without duplicating entire programs.',
  },
  {
    id: 'fb-ext-olivia-grant',
    name: 'Olivia Grant',
    role: 'Omnichannel Experience Manager',
    companyContext: 'Canada · Department store · CX',
    rating: 4.5,
    sentiment: 'Positive' as const,
    category: 'Value Delivered' as const,
    review:
      'Omnichannel handoffs show up as owned workflows—store, app, and care stop blaming the “black box.”',
    likes: 'Journey-level visibility without a separate journey analytics contract.',
    improves: 'SKU-level drill for high-return categories only (performance).',
  },
  {
    id: 'fb-ext-vikram-shetty',
    name: 'Vikram Shetty',
    role: 'VP Operations',
    companyContext: 'India · Quick commerce · City operations',
    rating: 4,
    sentiment: 'Positive' as const,
    category: 'Operational Health' as const,
    review:
      'Peak-hour latency visibility paid for itself during a regional outage—we rerouted before customer complaints spiked.',
    likes: 'Operational health that respects rider and picker constraints.',
    improves: 'Tighter mobile exec view; some dashboards feel dense.',
  },
  {
    id: 'fb-ext-nadia-petrov',
    name: 'Nadia Petrov',
    role: 'AI Enablement Manager',
    companyContext: 'Germany · Automotive supplier · IT',
    rating: 5,
    sentiment: 'Positive' as const,
    category: 'Value Delivered' as const,
    review:
      'Enablement kits finally match how plants actually adopt tools—less slide-deck theater, more operational proof.',
    likes: 'Role-based onboarding paths that don’t infantilize engineers.',
    improves: 'Plant-floor kiosk mode for read-only KPIs.',
  },
  {
    id: 'fb-ext-carlos-mendes',
    name: 'Carlos Mendes',
    role: 'Revenue Intelligence Analyst',
    companyContext: 'Brazil · B2B marketplace · Rev intel',
    rating: 3.5,
    sentiment: 'Mixed' as const,
    category: 'Cost Optimization' as const,
    review:
      'Routing recommendations are directionally useful; the optimization assumptions need clearer footnotes for finance.',
    likes: 'Honest about trade-offs between cost and quality.',
    improves: 'Sensitivity tables embedded next to each recommendation.',
  },
  {
    id: 'fb-ext-rebecca-thorne',
    name: 'Rebecca Thorne',
    role: 'Vendor Management Lead',
    companyContext: 'UK · NHS shared services · Digital',
    rating: 4,
    sentiment: 'Mixed' as const,
    category: 'Cost Optimization' as const,
    review:
      'Vendor scorecards improved our renewal conversation, though integration maturity varies wildly by supplier.',
    likes: 'Contract-friendly language on usage and performance.',
    improves: 'Standard DPIA appendix aligned to NHS templates.',
  },
  {
    id: 'fb-ext-anton-kovalenko',
    name: 'Anton Kovalenko',
    role: 'Process Automation Manager',
    companyContext: 'Ukraine · Shared services center · Banking back-office',
    rating: 4.5,
    sentiment: 'Positive' as const,
    category: 'Value Delivered' as const,
    review:
      'Automation council meetings shortened—exceptions are visible, not buried in RPA logs.',
    likes: 'Workflow ownership is explicit in the UI.',
    improves: 'BPMN export for teams still on legacy orchestration.',
  },
  {
    id: 'fb-ext-mireille-dubost',
    name: 'Mireille Dubost',
    role: 'Service Reliability Director',
    companyContext: 'France · Cloud-native insurer · SRE',
    rating: 5,
    sentiment: 'Positive' as const,
    category: 'Operational Health' as const,
    review:
      'Runbooks and agent health finally share a clock—we stopped duplicating incident context in three tools.',
    likes: 'Incident awareness that respects on-call mental load.',
    improves: 'Post-incident review templates with prefilled timelines.',
  },
  {
    id: 'fb-ext-ethan-caldwell',
    name: 'Ethan Caldwell',
    role: 'Regional Retail Controller',
    companyContext: 'US · Sporting goods · Finance',
    rating: 4,
    sentiment: 'Positive' as const,
    category: 'Cost Optimization' as const,
    review:
      'Closed-loop on premium model overuse gave us a lever we could defend in quarterly close commentary.',
    likes: 'Finance-grade framing without pretending precision we don’t have.',
    improves: 'FX-aware cost views for regional rollups.',
  },
  {
    id: 'fb-ext-dr-sana-rahman',
    name: 'Dr. Sana Rahman',
    role: 'Clinical Informatics Director',
    companyContext: 'US · Academic medical center',
    rating: 4.5,
    sentiment: 'Positive' as const,
    category: 'Governance' as const,
    review:
      'Clinical workflows get defensible documentation for why an assistant suggested a pathway—still requires clinician judgment.',
    likes: 'Auditability that doesn’t read like marketing.',
    improves: 'Epic-specific activity feeds for informatics reviewers.',
  },
  {
    id: 'fb-ext-lucas-ferreira',
    name: 'Lucas Ferreira',
    role: 'Network Operations VP',
    companyContext: 'Portugal · National telecom · Core network',
    rating: 3.5,
    sentiment: 'Mixed' as const,
    category: 'Operational Health' as const,
    review:
      'Good for app-layer agent latency; tying it to radio access congestion still needs our own overlays.',
    likes: 'Honest scope boundaries in the docs.',
    improves: 'Optional ingestion of RAN KPIs for correlation views.',
  },
  {
    id: 'fb-ext-yuki-taneda',
    name: 'Yuki Taneda',
    role: 'Supply Chain Systems Lead',
    companyContext: 'Japan · Electronics manufacturing',
    rating: 4.5,
    sentiment: 'Positive' as const,
    category: 'Operational Health' as const,
    review:
      'Supplier delay bots and internal planners now share the same health signals—fewer “system says fine, floor says not fine” moments.',
    likes: 'Scaling concerns surfaced before we doubled transaction volume.',
    improves: 'Batch job windows overlaid on agent traffic.',
  },
  {
    id: 'fb-ext-dimitra-papadopoulos',
    name: 'Dimitra Papadopoulos',
    role: 'B2B Customer Advisory Director',
    companyContext: 'Greece · Shipping software',
    rating: 3.5,
    sentiment: 'Mixed' as const,
    category: 'Agent Effectiveness & Trust' as const,
    review:
      'Advisory councils asked hard questions about explainability; we had partial answers—better than none, not yet complete.',
    likes: 'Credible demos under pressure.',
    improves: 'Customer-safe anonymized examples for trust reviews.',
  },
  {
    id: 'fb-ext-marcus-stein',
    name: 'Marcus Stein',
    role: 'Legal Operations Counsel',
    companyContext: 'Germany · Chemical conglomerate',
    rating: 3,
    sentiment: 'Critical' as const,
    category: 'Governance' as const,
    review:
      'Some dashboards feel too dense for executives—we need one-page attestations, not twenty tiles, for committee packets.',
    likes: 'Underlying data seems sound when we dig.',
    improves: 'Executive one-pagers with mandatory narrative slots.',
  },
  {
    id: 'fb-ext-ines-almeida',
    name: 'Inês Almeida',
    role: 'Field Service Manager',
    companyContext: 'Portugal · Commercial HVAC · Service',
    rating: 4,
    sentiment: 'Mixed' as const,
    category: 'Value Delivered' as const,
    review:
      'Technicians adopt it when the assistant cites the right manual section; onboarding friction for crews without SSO was real.',
    likes: 'Practical job aids embedded in feedback loops.',
    improves: 'SMS-friendly deep links for low-friction auth.',
  },
  {
    id: 'fb-ext-taylor-nguyen',
    name: 'Taylor Nguyen',
    role: 'Corporate Development Analyst',
    companyContext: 'US · Diversified holding company',
    rating: 4.5,
    sentiment: 'Positive' as const,
    category: 'Cost Optimization' as const,
    review:
      'M&A diligence on AI spend got faster—we could compare run-rate assumptions across targets without a bespoke model each time.',
    likes: 'Scenario thinking that doesn’t pretend certainty.',
    improves: 'Locked PDF export for data room sharing.',
  },
  {
    id: 'fb-ext-amina-diallo',
    name: 'Amina Diallo',
    role: 'Treasury Operations Lead',
    companyContext: 'Senegal · Regional bank · Treasury',
    rating: 3.5,
    sentiment: 'Mixed' as const,
    category: 'Cost Optimization' as const,
    review:
      'Useful for forecasting token-like usage patterns; FX and settlement timing assumptions still need our own layer.',
    likes: 'Clear separation of vendor invoice vs. internal allocation.',
    improves: 'Treasury calendar overlays for month-end spikes.',
  },
  {
    id: 'fb-ext-grzegorz-milewski',
    name: 'Grzegorz Milewski',
    role: 'Quality Assurance Manager',
    companyContext: 'Poland · Food manufacturing · QA',
    rating: 4,
    sentiment: 'Mixed' as const,
    category: 'Agent Effectiveness & Trust' as const,
    review:
      'Lot trace assistants need airtight confidence calibration; we’re close, but QA won’t sign until false-positive rates are trended.',
    likes: 'Traceable citations to batch records when they work.',
    improves: 'Formal sign-off workflow for model updates affecting QA.',
  },
  {
    id: 'fb-ext-zara-hussein',
    name: 'Zara Hussein',
    role: 'Employee Experience Lead',
    companyContext: 'UAE · Conglomerate · HR tech',
    rating: 4.5,
    sentiment: 'Positive' as const,
    category: 'Value Delivered' as const,
    review:
      'HRBPs finally see which policy bots drive tickets—targeted fixes instead of org-wide retraining.',
    likes: 'Sensitive tone metrics without feeling surveillance-heavy.',
    improves: 'Anonymization thresholds configurable by region.',
  },
  {
    id: 'fb-ext-kirsten-van-den-berg',
    name: 'Kirsten van den Berg',
    role: 'Digital Workplace Lead',
    companyContext: 'Belgium · Pharma commercial · IT',
    rating: 4.5,
    sentiment: 'Positive' as const,
    category: 'Operational Health' as const,
    review:
      'Helpdesk copilot health is visible next to classic ticket KPIs—IT governance finally has a shared dashboard.',
    likes: 'Integration maturity called out honestly in release notes.',
    improves: 'Entra ID group-based access recipes.',
  },
  {
    id: 'fb-ext-malcolm-reed',
    name: 'Malcolm Reed',
    role: 'Risk Analytics Manager',
    companyContext: 'UK · Investment management · Risk',
    rating: 3,
    sentiment: 'Critical' as const,
    category: 'Agent Effectiveness & Trust' as const,
    review:
      'Model explainability for client-facing advice still feels thin under stress scenarios—we need scenario-conditioned rationales.',
    likes: 'Solid engineering culture in how you surface uncertainty.',
    improves: 'Regulator-style scenario library with expected outputs.',
  },
  {
    id: 'fb-ext-elodie-martin',
    name: 'Élodie Martin',
    role: 'Loyalty Program Director',
    companyContext: 'France · Airline · CRM',
    rating: 5,
    sentiment: 'Positive' as const,
    category: 'Value Delivered' as const,
    review:
      'Elite tier complaints dropped when we tuned assistants using the same quality bar as human agents.',
    likes: 'Executive reporting that respects loyalty economics.',
    improves: 'Fraud-adjacent intent tagging for mileage edge cases.',
  },
  {
    id: 'fb-ext-junseo-park',
    name: 'Junseo Park',
    role: 'E-commerce Operations Lead',
    companyContext: 'South Korea · Beauty marketplace',
    rating: 4.5,
    sentiment: 'Positive' as const,
    category: 'Operational Health' as const,
    review:
      'Campaign-hour load tests lined up with what we saw in Agent360—fewer post-mortems arguing about “unexpected traffic.”',
    likes: 'Clear scaling signals before flash events.',
    improves: 'CDN edge cache correlation (optional module).',
  },
  {
    id: 'fb-ext-chioma-okeke',
    name: 'Chioma Okeke',
    role: 'Payments Product Owner',
    companyContext: 'Kenya · Fintech · Payments',
    rating: 4,
    sentiment: 'Mixed' as const,
    category: 'Operational Health' as const,
    review:
      'PSP latency overlays helped, but alert fatigue kicked in until we tuned thresholds—defaults skew aggressive.',
    likes: 'Incident awareness tied to customer-visible failures.',
    improves: 'Progressive alerting: whisper, then page.',
  },
  {
    id: 'fb-ext-rajesh-iyer',
    name: 'Rajesh Iyer',
    role: 'Infrastructure Program Director',
    companyContext: 'US · Healthcare payer · Infrastructure',
    rating: 4.5,
    sentiment: 'Positive' as const,
    category: 'Operational Health' as const,
    review:
      'Migration weekends got calmer—agent traffic shifts were visible next to cutover milestones.',
    likes: 'Program view that doesn’t ignore AI as “just an app.”',
    improves: 'Change calendar integration with ServiceNow.',
  },
  {
    id: 'fb-ext-noah-friedman',
    name: 'Noah Friedman',
    role: 'Sustainability Reporting Manager',
    companyContext: 'US · Industrial conglomerate · ESG',
    rating: 4,
    sentiment: 'Mixed' as const,
    category: 'Governance' as const,
    review:
      'ESG questionnaire assistants need defensible citations; we’re piloting, but reviewers still spot gaps in source coverage.',
    likes: 'Serious tone—no greenwashing shortcuts in the UI.',
    improves: 'Source coverage maps for each disclosure cluster.',
  },
  {
    id: 'fb-ext-sophie-march',
    name: 'Sophie March',
    role: 'Franchise Business Coach',
    companyContext: 'Australia · QSR franchise system',
    rating: 4.5,
    sentiment: 'Positive' as const,
    category: 'Value Delivered' as const,
    review:
      'Franchisees trust numbers when they mirror store reality—we finally have that parity on assistant-driven tasks.',
    likes: 'Field-friendly language; minimal jargon.',
    improves: 'Benchmarks by store format (drive-thru vs. mall).',
  },
  {
    id: 'fb-ext-ibrahim-saad',
    name: 'Ibrahim Saad',
    role: 'Clinical Operations Coordinator',
    companyContext: 'Egypt · Private hospital group',
    rating: 3.5,
    sentiment: 'Mixed' as const,
    category: 'Operational Health' as const,
    review:
      'Scheduling assistant reliability improved, yet integration maturity with our PAS still causes duplicate patient touches.',
    likes: 'Clinician-readable latency notes.',
    improves: 'PAS-specific error codes in plain language.',
  },
  {
    id: 'fb-ext-linda-chen',
    name: 'Linda Chen',
    role: 'Broker-Dealer Compliance Officer',
    companyContext: 'US · FINRA member · Compliance',
    rating: 3,
    sentiment: 'Critical' as const,
    category: 'Governance' as const,
    review:
      'Supervisory workflows need immutable records of what the agent advised versus what the rep executed—today that’s too soft.',
    likes: 'The roadmap acknowledges retention and WORM storage.',
    improves: 'WORM-ready export and legal hold tagging.',
  },
  {
    id: 'fb-ext-mateo-riera',
    name: 'Mateo Riera',
    role: 'Field Marketing Director',
    companyContext: 'Spain · Beverage distributor',
    rating: 4.5,
    sentiment: 'Positive' as const,
    category: 'Value Delivered' as const,
    review:
      'Promo assistant misfires dropped once marketing and ops shared Agent360’s quality bar.',
    likes: 'Cross-team alignment without a quarterly war room.',
    improves: 'Regional brand guideline packs as first-class objects.',
  },
  {
    id: 'fb-ext-priya-sundaram',
    name: 'Priya Sundaram',
    role: 'Data Platform Owner',
    companyContext: 'US · Logistics SaaS · Data platform',
    rating: 5,
    sentiment: 'Positive' as const,
    category: 'Operational Health' as const,
    review:
      'Lakehouse feeds stabilized after we caught schema drift in agent metric exports early.',
    likes: 'Contract testing hints saved us a weekend rollback.',
    improves: 'Protobuf/Avro schema registry hooks.',
  },
  {
    id: 'fb-ext-dana-choi',
    name: 'Dana Choi',
    role: 'Application Security Engineer',
    companyContext: 'South Korea · Enterprise IT · AppSec',
    rating: 3.5,
    sentiment: 'Mixed' as const,
    category: 'Governance' as const,
    review:
      'Security review was thorough; least-privilege templates for agent tool access still need sharper defaults for enterprise.',
    likes: 'Transparent permission graphs.',
    improves: 'CIS-aligned baseline profiles per industry.',
  },
  {
    id: 'fb-ext-emma-walsh',
    name: 'Emma Walsh',
    role: 'Customer Community Manager',
    companyContext: 'Ireland · Developer tools · Community',
    rating: 4.5,
    sentiment: 'Positive' as const,
    category: 'Agent Effectiveness & Trust' as const,
    review:
      'Community moderators trust escalations more—bad answers are labeled with reproducible context.',
    likes: 'Human corrections that don’t vanish into Slack threads.',
    improves: 'Public changelog entries when trust rubrics change.',
  },
  {
    id: 'fb-ext-kevin-zhao',
    name: 'Kevin Zhao',
    role: 'Sales Operations Analyst',
    companyContext: 'China · Industrial B2B · Sales ops',
    rating: 3.5,
    sentiment: 'Mixed' as const,
    category: 'Cost Optimization' as const,
    review:
      'Routing suggestions clash occasionally with regional discount policy—we need clearer ownership when rules disagree.',
    likes: 'Spend visibility by sales theater.',
    improves: 'Policy precedence debugger for routing conflicts.',
  },
  {
    id: 'fb-ext-silvia-romano',
    name: 'Silvia Romano',
    role: 'Incident Commander',
    companyContext: 'Italy · Cloud marketplace · Operations',
    rating: 5,
    sentiment: 'Positive' as const,
    category: 'Operational Health' as const,
    review:
      'Single source of truth during sev-1s—agent degradation sat next to core API graphs.',
    likes: 'Low ceremony; high signal.',
    improves: 'War-room timer overlays for mitigation checkpoints.',
  },
  {
    id: 'fb-ext-natalie-brooks',
    name: 'Natalie Brooks',
    role: 'Pricing Strategy Manager',
    companyContext: 'US · Airlines · Revenue management',
    rating: 4.5,
    sentiment: 'Positive' as const,
    category: 'Cost Optimization' as const,
    review:
      'Experimentation on model tiers mapped cleanly to margin guardrails—finance signed off faster.',
    likes: 'ROI confidence without overclaiming precision.',
    improves: 'Fare-class sensitivity overlays (anonymized).',
  },
  {
    id: 'fb-ext-ahmed-farooqi',
    name: 'Ahmed Farooqi',
    role: 'Voice of Customer Analyst',
    companyContext: 'Pakistan · Telco · CX insights',
    rating: 4,
    sentiment: 'Positive' as const,
    category: 'Value Delivered' as const,
    review:
      'Verbatim themes and agent failures finally land in the same workshop deck—less reconciliation.',
    likes: 'Honest about sampling bias in feedback ingestion.',
    improves: 'Native connectors for our survey platform.',
  },
  {
    id: 'fb-ext-brandon-cho',
    name: 'Brandon Cho',
    role: 'Cloud FinOps Lead',
    companyContext: 'US · Enterprise SaaS · FinOps',
    rating: 4.5,
    sentiment: 'Positive' as const,
    category: 'Cost Optimization' as const,
    review:
      'Unit economics by feature flag made our engineering roadmap conversation adult again.',
    likes: 'Shows premium model overuse without shaming teams.',
    improves: 'Reserved capacity modeling for committed use discounts.',
  },
  {
    id: 'fb-ext-marcus-lee',
    name: 'Marcus Lee',
    role: 'Campus IT Director',
    companyContext: 'US · Large public university',
    rating: 4.5,
    sentiment: 'Positive' as const,
    category: 'Operational Health' as const,
    review:
      'Semester start was smoother—assistant latency issues surfaced before the helpdesk melted.',
    likes: 'Operational accountability visible to non-specialists.',
    improves: 'Student privacy redaction presets.',
  },
  {
    id: 'fb-ext-rose-okonkwo',
    name: 'Rose Okonkwo',
    role: 'Pharmacy Benefits Manager',
    companyContext: 'US · Regional health plan',
    rating: 4,
    sentiment: 'Mixed' as const,
    category: 'Governance' as const,
    review:
      'Compliance readiness is improving; prior authorization bots still need clearer appeal-path documentation.',
    likes: 'Audit-friendly language in release notes.',
    improves: 'State-specific regulatory overlays.',
  },
  {
    id: 'fb-ext-timo-virtanen',
    name: 'Timo Virtanen',
    role: 'Aircraft Maintenance Planner',
    companyContext: 'Finland · MRO provider · Aviation',
    rating: 4,
    sentiment: 'Positive' as const,
    category: 'Operational Health' as const,
    review:
      'Parts availability assistant errors dropped once reliability views included supplier lead-time variance.',
    likes: 'Regulatory-adjacent workflows treated with appropriate rigor.',
    improves: 'MRO system connectors for tail-specific histories.',
  },
  {
    id: 'fb-ext-christopher-adeyemi',
    name: 'Christopher Adeyemi',
    role: 'Mining Operations Analyst',
    companyContext: 'South Africa · Mining · Remote sites',
    rating: 4.5,
    sentiment: 'Positive' as const,
    category: 'Value Delivered' as const,
    review:
      'Field supervisors trust summaries when satellite links wobble—offline snapshots helped shift handoffs.',
    likes: 'Pragmatic about connectivity constraints.',
    improves: 'Rugged-device friendly contrast mode.',
  },
  {
    id: 'fb-ext-veronica-patel',
    name: 'Veronica Patel',
    role: 'Public Relations Director',
    companyContext: 'India · Conglomerate · Corporate comms',
    rating: 3.5,
    sentiment: 'Mixed' as const,
    category: 'Governance' as const,
    review:
      'Crisis comms drills surfaced gaps in how AI-generated talking points are approved—work in progress.',
    likes: 'Clear escalation paths for sensitive narratives.',
    improves: 'Legal pre-approval queues with timestamps.',
  },
  {
    id: 'fb-ext-jonas-eriksson',
    name: 'Jonas Eriksson',
    role: 'Fleet Telematics Lead',
    companyContext: 'Sweden · Logistics · Fleet',
    rating: 4.5,
    sentiment: 'Positive' as const,
    category: 'Operational Health' as const,
    review:
      'Dispatch assistants and telematics alerts finally correlate—fewer “ghost delays” in customer comms.',
    likes: 'Provider reliability called out honestly.',
    improves: 'Edge case maps for roaming SIM handoffs.',
  },
  {
    id: 'fb-ext-michelle-girard',
    name: 'Michelle Girard',
    role: 'Insurance Product Manager',
    companyContext: 'Québec · P&C insurer · Product',
    rating: 4,
    sentiment: 'Positive' as const,
    category: 'Agent Effectiveness & Trust' as const,
    review:
      'Policy interpretation assistants improved quote consistency; human reviewers spend time on edge statutes only.',
    likes: 'Confidence bands that match actuarial caution.',
    improves: 'Province-specific regulatory diff alerts.',
  },
  {
    id: 'fb-ext-saad-malik',
    name: 'Saad Malik',
    role: 'Hypermarket Store Director',
    companyContext: 'Saudi Arabia · Grocery retail · Store ops',
    rating: 4.5,
    sentiment: 'Positive' as const,
    category: 'Value Delivered' as const,
    review:
      'Shrink and customer complaints tied to assistant errors are visible weekly—store council meetings are shorter.',
    likes: 'Non-technical language that my leads actually use.',
    improves: 'Arabic RTL layout polish in a few dense tables.',
  },
  {
    id: 'fb-ext-george-nkrumah',
    name: 'George Nkrumah',
    role: 'Wholesale Distribution VP',
    companyContext: 'Ghana · FMCG distribution',
    rating: 5,
    sentiment: 'Positive' as const,
    category: 'Value Delivered' as const,
    review:
      'Credit and collections assistants with clear trust metrics reduced escalations to my desk.',
    likes: 'Executive reporting that respects distributor relationships.',
    improves: 'Mobile data-light dashboards for reps on the road.',
  },
  {
    id: 'fb-ext-elena-costas',
    name: 'Elena Costas',
    role: 'AI Skeptic / Store Lead',
    companyContext: 'Spain · Electronics retail · Floor leadership',
    rating: 3,
    sentiment: 'Critical' as const,
    category: 'Agent Effectiveness & Trust' as const,
    review:
      'Still wary of vendor narratives—Agent360 shows receipts, but onboarding for floor staff is slow and trust scoring feels blunt for returns edge cases.',
    likes: 'When it’s wrong, we can usually see why.',
    improves: 'Two-tap “escalate to human” with context preserved; sharper calibration on low-confidence handoffs.',
  },
] as const
