import type { ApiComparisonDetail } from './detailTypes'
import { apiDrawerDetailsById } from './drawerDetails'

export type ApiComparisonRow = {
  id: string
  api: string
  provider: string
  avgLatency: string
  availability: string
  errorRate: string
  retryRate: string
  rateLimitFrequency: string
  operationalStability: 'Excellent' | 'Strong' | 'Moderate' | 'Watch'
  bestUseCase: string
  detail: ApiComparisonDetail
}

export type { ApiComparisonDetail } from './detailTypes'

export const apiComparisonRows: ApiComparisonRow[] = [
  {
    id: 'salesforce',
    api: 'Salesforce API',
    provider: 'Salesforce',
    avgLatency: '240ms',
    availability: '99.94%',
    errorRate: '0.4%',
    retryRate: '1.8%',
    rateLimitFrequency: 'Low',
    operationalStability: 'Strong',
    bestUseCase: 'CRM-backed support and sales tools',
    detail: apiDrawerDetailsById.salesforce,
  },
  {
    id: 'zendesk',
    api: 'Zendesk API',
    provider: 'Zendesk',
    avgLatency: '310ms',
    availability: '99.78%',
    errorRate: '1.1%',
    retryRate: '4.2%',
    rateLimitFrequency: 'Medium',
    operationalStability: 'Moderate',
    bestUseCase: 'Ticket search and macro automation',
    detail: apiDrawerDetailsById.zendesk,
  },
  {
    id: 'jira',
    api: 'Jira API',
    provider: 'Atlassian',
    avgLatency: '275ms',
    availability: '99.91%',
    errorRate: '0.5%',
    retryRate: '2.1%',
    rateLimitFrequency: 'Low',
    operationalStability: 'Strong',
    bestUseCase: 'Issue linking and ops workflows',
    detail: apiDrawerDetailsById.jira,
  },
  {
    id: 'slack',
    api: 'Slack API',
    provider: 'Slack',
    avgLatency: '195ms',
    availability: '99.89%',
    errorRate: '0.6%',
    retryRate: '2.6%',
    rateLimitFrequency: 'High',
    operationalStability: 'Strong',
    bestUseCase: 'Notifications and internal routing',
    detail: apiDrawerDetailsById.slack,
  },
  {
    id: 'stripe',
    api: 'Stripe API',
    provider: 'Stripe',
    avgLatency: '180ms',
    availability: '99.99%',
    errorRate: '0.2%',
    retryRate: '0.9%',
    rateLimitFrequency: 'Low',
    operationalStability: 'Excellent',
    bestUseCase: 'Payments and billing tool calls',
    detail: apiDrawerDetailsById.stripe,
  },
  {
    id: 'hubspot',
    api: 'HubSpot API',
    provider: 'HubSpot',
    avgLatency: '265ms',
    availability: '99.86%',
    errorRate: '0.7%',
    retryRate: '2.9%',
    rateLimitFrequency: 'Medium',
    operationalStability: 'Strong',
    bestUseCase: 'Marketing and lead context',
    detail: apiDrawerDetailsById.hubspot,
  },
  {
    id: 'servicenow',
    api: 'ServiceNow API',
    provider: 'ServiceNow',
    avgLatency: '340ms',
    availability: '99.72%',
    errorRate: '1.2%',
    retryRate: '3.6%',
    rateLimitFrequency: 'Medium',
    operationalStability: 'Moderate',
    bestUseCase: 'ITSM integrations',
    detail: apiDrawerDetailsById.servicenow,
  },
  {
    id: 'confluence',
    api: 'Confluence API',
    provider: 'Atlassian',
    avgLatency: '290ms',
    availability: '99.90%',
    errorRate: '0.55%',
    retryRate: '2.2%',
    rateLimitFrequency: 'Low',
    operationalStability: 'Strong',
    bestUseCase: 'Internal documentation retrieval',
    detail: apiDrawerDetailsById.confluence,
  },
  {
    id: 'notion',
    api: 'Notion API',
    provider: 'Notion',
    avgLatency: '320ms',
    availability: '99.84%',
    errorRate: '0.8%',
    retryRate: '3.1%',
    rateLimitFrequency: 'Medium',
    operationalStability: 'Moderate',
    bestUseCase: 'Playbooks and knowledge sync',
    detail: apiDrawerDetailsById.notion,
  },
  {
    id: 'google-calendar',
    api: 'Google Calendar API',
    provider: 'Google',
    avgLatency: '210ms',
    availability: '99.93%',
    errorRate: '0.35%',
    retryRate: '1.5%',
    rateLimitFrequency: 'Medium',
    operationalStability: 'Strong',
    bestUseCase: 'Scheduling and handoff tooling',
    detail: apiDrawerDetailsById['google-calendar'],
  },
  {
    id: 'internal-crm',
    api: 'Internal CRM API',
    provider: 'Internal',
    avgLatency: '185ms',
    availability: '99.68%',
    errorRate: '1.4%',
    retryRate: '5.2%',
    rateLimitFrequency: 'Low',
    operationalStability: 'Watch',
    bestUseCase: 'First-party customer records',
    detail: apiDrawerDetailsById['internal-crm'],
  },
  {
    id: 'delivery-tracking',
    api: 'Delivery Tracking API',
    provider: 'Logistics Partner',
    avgLatency: '380ms',
    availability: '99.61%',
    errorRate: '1.6%',
    retryRate: '6.4%',
    rateLimitFrequency: 'Low',
    operationalStability: 'Watch',
    bestUseCase: 'Shipment status and ETA tools',
    detail: apiDrawerDetailsById['delivery-tracking'],
  },
  {
    id: 'identity-auth',
    api: 'Identity / Auth API',
    provider: 'Internal IAM',
    avgLatency: '95ms',
    availability: '99.97%',
    errorRate: '0.15%',
    retryRate: '0.4%',
    rateLimitFrequency: 'Low',
    operationalStability: 'Excellent',
    bestUseCase: 'Token validation for all tool calls',
    detail: apiDrawerDetailsById['identity-auth'],
  },
]
