import type { ApiComparisonDetail } from './detailTypes'

const sp = (...n: number[]) => n

export const apiDrawerDetailsById: Record<string, ApiComparisonDetail> = {
  salesforce: {
    summary: 'Stable enterprise CRM dependency with predictable daytime load.',
    operationalNotes: ['Watch composite request batching', 'Cache stable object reads'],
    agentToolingContext:
      'Primary CRM surface for sales and support agents issuing SOQL-backed lookups, case updates, and account enrichment during live chats.',
    dependencyOverview: {
      productionAgentCount: 6,
      workflowCount: 14,
      criticality: 'High',
      fallbackEnabled: true,
      volumeClass: 'High-volume',
      primaryWorkflows: [
        'Support Assistant — case context & entitlements',
        'Sales Copilot — opportunity and contact enrichment',
        'Escalation Router — account hierarchy resolution',
      ],
      agentNames: [
        'Support Assistant',
        'Sales Copilot',
        'Renewals Agent',
        'Escalation Router',
        'Onboarding Guide',
        'Deal Desk Helper',
      ],
      notes: [
        'Critical dependency for Support Assistant quote-to-case flows.',
        'Read-heavy /accounts/query dominates off-peak traffic.',
      ],
    },
    runtimeBreakdown: {
      network: '38%',
      processing: '44%',
      authOverhead: '9%',
      retryOverhead: '6%',
      fallbackExecution: '3%',
    },
    timeline: [
      { timeUtc: '06:14 UTC', message: 'Composite API batch latency exceeded SLO (EU pod)', tone: 'warning' },
      { timeUtc: '06:22 UTC', message: 'Agent tool concurrency throttle applied — Support Assistant', tone: 'neutral' },
      { timeUtc: '06:35 UTC', message: '/contacts/search p95 normalized after cache warm', tone: 'positive' },
    ],
    endpoints: [
      {
        path: '/contacts/search',
        avgLatency: '228ms',
        p95Latency: '412ms',
        errorRate: '0.35%',
        timeoutRate: '0.12%',
        requestsPerMin: '420 rpm',
        retryRate: '1.6%',
        availability: '99.95%',
        lastIncident: 'Degraded · 6h ago',
        operationalStatus: 'Healthy',
        severityLabel: 'OK',
        insight: 'Latency aligns with agent peak; SOQL complexity drives tail.',
        latencySparkline: sp(42, 44, 41, 48, 52, 49, 45, 43, 46, 44),
      },
      {
        path: '/cases/update',
        avgLatency: '256ms',
        p95Latency: '480ms',
        errorRate: '0.52%',
        timeoutRate: '0.22%',
        requestsPerMin: '186 rpm',
        retryRate: '2.1%',
        availability: '99.91%',
        lastIncident: 'Timeout · 1d ago',
        operationalStatus: 'Healthy',
        severityLabel: 'OK',
        insight: 'Write path stable; idempotent retries from agent tools are bounded.',
        latencySparkline: sp(48, 50, 47, 51, 55, 52, 49, 48, 50, 47),
      },
      {
        path: '/accounts/query',
        avgLatency: '198ms',
        p95Latency: '360ms',
        errorRate: '0.28%',
        timeoutRate: '0.08%',
        requestsPerMin: '512 rpm',
        retryRate: '1.4%',
        availability: '99.96%',
        lastIncident: 'None · 7d',
        operationalStatus: 'Healthy',
        severityLabel: 'OK',
        insight: 'Highest RPM — cached reads reduce load on primary org.',
        latencySparkline: sp(38, 40, 39, 41, 44, 42, 40, 39, 41, 40),
      },
      {
        path: '/customer/profile',
        avgLatency: '271ms',
        p95Latency: '505ms',
        errorRate: '0.61%',
        timeoutRate: '0.31%',
        requestsPerMin: '94 rpm',
        retryRate: '2.4%',
        availability: '99.88%',
        lastIncident: 'Schema drift · 3d ago',
        operationalStatus: 'Degraded',
        severityLabel: 'Watch',
        insight: 'Custom fields occasionally mismatch agent tool schema — contract tests flagged.',
        latencySparkline: sp(52, 54, 58, 62, 60, 57, 55, 56, 58, 55),
      },
    ],
  },
  zendesk: {
    summary: 'Higher tail latency; timeout-sensitive under search load.',
    operationalNotes: ['Tune backoff on search endpoints', 'Isolate EU traffic if needed'],
    agentToolingContext:
      'Support agents rely on ticket creation, macro application, and user lookup tools during live conversations and async follow-ups.',
    dependencyOverview: {
      productionAgentCount: 5,
      workflowCount: 11,
      criticality: 'Critical',
      fallbackEnabled: true,
      volumeClass: 'High-volume',
      primaryWorkflows: [
        'Support Assistant — ticket create/update',
        'Tier-2 Triage — user and org resolution',
        'Macro Bot — suggested replies from macros/list',
      ],
      agentNames: ['Support Assistant', 'Tier-2 Triage', 'Macro Bot', 'CSAT Follow-up', 'Escalation Router'],
      notes: [
        'Critical dependency for Support Assistant real-time ticketing.',
        'EU shard shows elevated timeout correlation with peak support hours.',
      ],
    },
    runtimeBreakdown: {
      network: '32%',
      processing: '41%',
      authOverhead: '11%',
      retryOverhead: '12%',
      fallbackExecution: '4%',
    },
    timeline: [
      { timeUtc: '09:12 UTC', message: 'Zendesk timeout rate exceeded threshold on /tickets/create', tone: 'critical' },
      { timeUtc: '09:28 UTC', message: 'Retry amplification detected — agent batch size reduced', tone: 'warning' },
      { timeUtc: '09:41 UTC', message: 'Service recovered — p95 within SLO', tone: 'positive' },
    ],
    endpoints: [
      {
        path: '/tickets/create',
        avgLatency: '348ms',
        p95Latency: '720ms',
        errorRate: '1.4%',
        timeoutRate: '0.82%',
        requestsPerMin: '142 rpm',
        retryRate: '5.8%',
        availability: '99.72%',
        lastIncident: 'Timeout spike · 2h ago',
        operationalStatus: 'Degraded',
        severityLabel: 'Elevated',
        insight: '/tickets/create latency spikes during peak support hours — aligns with agent concurrency.',
        latencySparkline: sp(55, 58, 62, 70, 78, 74, 68, 65, 63, 60),
      },
      {
        path: '/tickets/update',
        avgLatency: '302ms',
        p95Latency: '590ms',
        errorRate: '1.05%',
        timeoutRate: '0.55%',
        requestsPerMin: '208 rpm',
        retryRate: '4.2%',
        availability: '99.78%',
        lastIncident: 'Warning · 5h ago',
        operationalStatus: 'Degraded',
        severityLabel: 'Watch',
        insight: 'Update path sensitive to macro side-effects and custom triggers.',
        latencySparkline: sp(50, 52, 54, 58, 60, 57, 55, 54, 53, 52),
      },
      {
        path: '/users/search',
        avgLatency: '285ms',
        p95Latency: '540ms',
        errorRate: '0.88%',
        timeoutRate: '0.41%',
        requestsPerMin: '176 rpm',
        retryRate: '3.9%',
        availability: '99.81%',
        lastIncident: 'Auth refresh · 12h ago',
        operationalStatus: 'Healthy',
        severityLabel: 'Watch',
        insight: 'Search index lag occasionally increases agent handoff latency.',
        latencySparkline: sp(48, 50, 51, 54, 56, 54, 52, 51, 50, 49),
      },
      {
        path: '/macros/list',
        avgLatency: '198ms',
        p95Latency: '380ms',
        errorRate: '0.62%',
        timeoutRate: '0.18%',
        requestsPerMin: '64 rpm',
        retryRate: '2.8%',
        availability: '99.86%',
        lastIncident: 'None · 4d',
        operationalStatus: 'Healthy',
        severityLabel: 'OK',
        insight: 'Lightweight; used by Macro Bot for suggested reply scaffolding.',
        latencySparkline: sp(40, 41, 40, 42, 43, 42, 41, 40, 41, 40),
      },
    ],
  },
  jira: {
    summary: 'Reliable for scoped JQL and issue updates.',
    operationalNotes: ['Avoid unbounded project scans'],
    agentToolingContext:
      'Ops and engineering agents link customer issues to Jira work items, add comments, and run bounded JQL for incident correlation.',
    dependencyOverview: {
      productionAgentCount: 4,
      workflowCount: 9,
      criticality: 'High',
      fallbackEnabled: false,
      volumeClass: 'Medium',
      primaryWorkflows: ['Incident Linker', 'SRE Copilot', 'Release Notes Agent', 'Customer Escalation'],
      agentNames: ['Incident Linker', 'SRE Copilot', 'Release Notes Agent', 'Escalation Router'],
      notes: ['No automatic fallback — failures block issue sync until retry.'],
    },
    runtimeBreakdown: {
      network: '35%',
      processing: '46%',
      authOverhead: '10%',
      retryOverhead: '7%',
      fallbackExecution: '2%',
    },
    timeline: [
      { timeUtc: '04:05 UTC', message: 'JQL search rate limit approached — agents throttled', tone: 'warning' },
      { timeUtc: '04:18 UTC', message: 'Issue update success rate restored', tone: 'positive' },
    ],
    endpoints: [
      {
        path: '/rest/api/3/search',
        avgLatency: '312ms',
        p95Latency: '580ms',
        errorRate: '0.72%',
        timeoutRate: '0.28%',
        requestsPerMin: '118 rpm',
        retryRate: '2.8%',
        availability: '99.89%',
        lastIncident: 'Rate limit · 1d ago',
        operationalStatus: 'Healthy',
        severityLabel: 'OK',
        insight: 'Unbounded JQL from tools triggers guardrails in agent runtime.',
        latencySparkline: sp(48, 50, 52, 55, 54, 52, 50, 49, 51, 50),
      },
      {
        path: '/rest/api/3/issue',
        avgLatency: '268ms',
        p95Latency: '495ms',
        errorRate: '0.48%',
        timeoutRate: '0.19%',
        requestsPerMin: '95 rpm',
        retryRate: '2.0%',
        availability: '99.92%',
        lastIncident: 'None · 5d',
        operationalStatus: 'Healthy',
        severityLabel: 'OK',
        insight: 'Stable for create/update paths used by Incident Linker.',
        latencySparkline: sp(45, 46, 45, 47, 48, 47, 46, 45, 46, 45),
      },
      {
        path: '/rest/api/3/project',
        avgLatency: '225ms',
        p95Latency: '410ms',
        errorRate: '0.38%',
        timeoutRate: '0.11%',
        requestsPerMin: '38 rpm',
        retryRate: '1.5%',
        availability: '99.94%',
        lastIncident: 'None · 7d',
        operationalStatus: 'Healthy',
        severityLabel: 'OK',
        insight: 'Low volume; used for project scoping in agent tools.',
        latencySparkline: sp(40, 41, 40, 42, 41, 40, 41, 40, 41, 40),
      },
      {
        path: '/rest/api/3/comment',
        avgLatency: '242ms',
        p95Latency: '455ms',
        errorRate: '0.44%',
        timeoutRate: '0.15%',
        requestsPerMin: '72 rpm',
        retryRate: '1.9%',
        availability: '99.91%',
        lastIncident: 'None · 6d',
        operationalStatus: 'Healthy',
        severityLabel: 'OK',
        insight: 'Comment adds from agents batched where possible.',
        latencySparkline: sp(42, 43, 44, 45, 44, 43, 42, 43, 42, 43),
      },
    ],
  },
  slack: {
    summary: 'Fast API with frequent rate-limit pressure during peaks.',
    operationalNotes: ['Batch messages', 'Honor Retry-After headers'],
    agentToolingContext:
      'Agents post customer-safe summaries, fetch thread history for context, and resolve users by email for routing.',
    dependencyOverview: {
      productionAgentCount: 8,
      workflowCount: 19,
      criticality: 'High',
      fallbackEnabled: true,
      volumeClass: 'High-volume',
      primaryWorkflows: [
        'Support Assistant — thread handoffs',
        'Notify Bot — chat.postMessage',
        'On-call Router — user lookup',
      ],
      agentNames: [
        'Support Assistant',
        'Notify Bot',
        'On-call Router',
        'Standup Agent',
        'Incident Broadcaster',
        'Sales Copilot',
        'Deal Desk Helper',
        'Internal FAQ',
      ],
      notes: ['High-volume dependency across many production agents.', 'Fallback queues outbound when tier-4 limits hit.'],
    },
    runtimeBreakdown: {
      network: '28%',
      processing: '38%',
      authOverhead: '8%',
      retryOverhead: '18%',
      fallbackExecution: '8%',
    },
    timeline: [
      { timeUtc: '14:02 UTC', message: 'chat.postMessage retry storm during launch announcement', tone: 'warning' },
      { timeUtc: '14:11 UTC', message: 'Retry-After honored — agent send queue drained', tone: 'positive' },
    ],
    endpoints: [
      {
        path: '/chat.postMessage',
        avgLatency: '188ms',
        p95Latency: '395ms',
        errorRate: '0.72%',
        timeoutRate: '0.14%',
        requestsPerMin: '890 rpm',
        retryRate: '3.8%',
        availability: '99.87%',
        lastIncident: 'Elevated retries · 3h ago',
        operationalStatus: 'Degraded',
        severityLabel: 'Watch',
        insight: '/chat.postMessage experiencing elevated retry rate during internal broadcast peaks.',
        latencySparkline: sp(40, 42, 45, 52, 58, 55, 48, 44, 42, 41),
      },
      {
        path: '/conversations.history',
        avgLatency: '205ms',
        p95Latency: '420ms',
        errorRate: '0.58%',
        timeoutRate: '0.12%',
        requestsPerMin: '412 rpm',
        retryRate: '2.4%',
        availability: '99.90%',
        lastIncident: 'None · 2d',
        operationalStatus: 'Healthy',
        severityLabel: 'OK',
        insight: 'Thread hydration for conversational context — watch pagination depth.',
        latencySparkline: sp(42, 43, 44, 46, 45, 44, 43, 42, 43, 42),
      },
      {
        path: '/users.lookupByEmail',
        avgLatency: '162ms',
        p95Latency: '310ms',
        errorRate: '0.45%',
        timeoutRate: '0.08%',
        requestsPerMin: '228 rpm',
        retryRate: '1.9%',
        availability: '99.92%',
        lastIncident: 'None · 5d',
        operationalStatus: 'Healthy',
        severityLabel: 'OK',
        insight: 'Fast path for routing agent mentions and DM targets.',
        latencySparkline: sp(38, 39, 38, 40, 39, 38, 39, 38, 39, 38),
      },
      {
        path: '/files.upload',
        avgLatency: '312ms',
        p95Latency: '680ms',
        errorRate: '0.95%',
        timeoutRate: '0.35%',
        requestsPerMin: '54 rpm',
        retryRate: '4.1%',
        availability: '99.82%',
        lastIncident: 'Size limit · 1d ago',
        operationalStatus: 'Healthy',
        severityLabel: 'Watch',
        insight: 'Occasional failures on large exports from agent-generated reports.',
        latencySparkline: sp(48, 50, 52, 55, 54, 52, 50, 49, 48, 47),
      },
    ],
  },
  stripe: {
    summary: 'Highly reliable; strict idempotency and retry semantics.',
    operationalNotes: ['Use idempotency keys on all writes'],
    agentToolingContext:
      'Billing and support agents verify payments, search customers, and adjust subscriptions with idempotent tool calls.',
    dependencyOverview: {
      productionAgentCount: 5,
      workflowCount: 12,
      criticality: 'Critical',
      fallbackEnabled: true,
      volumeClass: 'High-volume',
      primaryWorkflows: ['Billing Agent', 'Support Assistant — refunds', 'Renewals Agent', 'Deal Desk Helper'],
      agentNames: ['Billing Agent', 'Support Assistant', 'Renewals Agent', 'Deal Desk Helper', 'Finance Copilot'],
      notes: [
        'Critical dependency for payment verification workflows.',
        'EU traffic shows slightly elevated retries — circuit-aware backoff enabled.',
      ],
    },
    runtimeBreakdown: {
      network: '22%',
      processing: '52%',
      authOverhead: '7%',
      retryOverhead: '14%',
      fallbackExecution: '5%',
    },
    timeline: [
      { timeUtc: '11:40 UTC', message: 'Stripe retries elevated in EU region — idempotency keys stable', tone: 'warning' },
      { timeUtc: '11:55 UTC', message: 'Payment endpoint availability recovered', tone: 'positive' },
    ],
    endpoints: [
      {
        path: '/customers/search',
        avgLatency: '165ms',
        p95Latency: '305ms',
        errorRate: '0.18%',
        timeoutRate: '0.05%',
        requestsPerMin: '320 rpm',
        retryRate: '0.8%',
        availability: '99.99%',
        lastIncident: 'None · 14d',
        operationalStatus: 'Healthy',
        severityLabel: 'OK',
        insight: 'Primary lookup for Billing Agent before subscription changes.',
        latencySparkline: sp(35, 36, 35, 37, 36, 35, 36, 35, 36, 35),
      },
      {
        path: '/payment_intents/create',
        avgLatency: '192ms',
        p95Latency: '355ms',
        errorRate: '0.22%',
        timeoutRate: '0.07%',
        requestsPerMin: '142 rpm',
        retryRate: '1.0%',
        availability: '99.98%',
        lastIncident: 'EU retry burst · 6h ago',
        operationalStatus: 'Healthy',
        severityLabel: 'OK',
        insight: 'Stripe payment endpoint availability recovered after regional blip.',
        latencySparkline: sp(38, 40, 42, 45, 44, 40, 38, 37, 38, 37),
      },
      {
        path: '/subscriptions/update',
        avgLatency: '205ms',
        p95Latency: '380ms',
        errorRate: '0.25%',
        timeoutRate: '0.08%',
        requestsPerMin: '88 rpm',
        retryRate: '1.1%',
        availability: '99.97%',
        lastIncident: 'None · 9d',
        operationalStatus: 'Healthy',
        severityLabel: 'OK',
        insight: 'Write path monitored for Renewals Agent plan changes.',
        latencySparkline: sp(40, 41, 42, 43, 42, 41, 40, 41, 40, 41),
      },
      {
        path: '/invoices/list',
        avgLatency: '178ms',
        p95Latency: '328ms',
        errorRate: '0.19%',
        timeoutRate: '0.06%',
        requestsPerMin: '196 rpm',
        retryRate: '0.85%',
        availability: '99.99%',
        lastIncident: 'None · 14d',
        operationalStatus: 'Healthy',
        severityLabel: 'OK',
        insight: 'Supports AR inquiries in Support Assistant billing threads.',
        latencySparkline: sp(36, 37, 36, 38, 37, 36, 37, 36, 37, 36),
      },
    ],
  },
  hubspot: {
    summary: 'Solid for property reads; watch burst limits.',
    operationalNotes: ['Cache contact reads with TTL'],
    agentToolingContext:
      'Marketing and sales agents enrich leads, pull deal stages, and sync campaign context into conversations.',
    dependencyOverview: {
      productionAgentCount: 4,
      workflowCount: 8,
      criticality: 'Standard',
      fallbackEnabled: true,
      volumeClass: 'Medium',
      primaryWorkflows: ['Sales Copilot', 'Marketing Agent', 'Onboarding Guide', 'CSAT Follow-up'],
      agentNames: ['Sales Copilot', 'Marketing Agent', 'Onboarding Guide', 'CSAT Follow-up'],
      notes: ['Burst limits correlate with batch contact enrichment tools.'],
    },
    runtimeBreakdown: {
      network: '30%',
      processing: '45%',
      authOverhead: '10%',
      retryOverhead: '11%',
      fallbackExecution: '4%',
    },
    timeline: [
      { timeUtc: '16:20 UTC', message: 'Contact search burst — agent batch size auto-reduced', tone: 'neutral' },
      { timeUtc: '16:34 UTC', message: 'API quota headroom restored', tone: 'positive' },
    ],
    endpoints: [
      {
        path: '/crm/v3/objects/contacts/search',
        avgLatency: '278ms',
        p95Latency: '520ms',
        errorRate: '0.82%',
        timeoutRate: '0.24%',
        requestsPerMin: '156 rpm',
        retryRate: '3.2%',
        availability: '99.85%',
        lastIncident: 'Burst · 8h ago',
        operationalStatus: 'Healthy',
        severityLabel: 'OK',
        insight: 'Dominates read traffic from Sales Copilot enrichment.',
        latencySparkline: sp(46, 48, 50, 52, 51, 49, 47, 46, 47, 46),
      },
      {
        path: '/crm/v3/objects/deals',
        avgLatency: '252ms',
        p95Latency: '475ms',
        errorRate: '0.68%',
        timeoutRate: '0.19%',
        requestsPerMin: '98 rpm',
        retryRate: '2.7%',
        availability: '99.88%',
        lastIncident: 'None · 3d',
        operationalStatus: 'Healthy',
        severityLabel: 'OK',
        insight: 'Deal stage reads for pipeline-aware agent replies.',
        latencySparkline: sp(44, 45, 46, 47, 46, 45, 44, 45, 44, 45),
      },
      {
        path: '/crm/v3/objects/tickets',
        avgLatency: '268ms',
        p95Latency: '498ms',
        errorRate: '0.74%',
        timeoutRate: '0.21%',
        requestsPerMin: '72 rpm',
        retryRate: '2.9%',
        availability: '99.86%',
        lastIncident: 'None · 4d',
        operationalStatus: 'Healthy',
        severityLabel: 'OK',
        insight: 'Ticket object bridges HubSpot with support agent context.',
        latencySparkline: sp(45, 46, 47, 48, 47, 46, 45, 46, 45, 46),
      },
      {
        path: '/crm/v3/owners',
        avgLatency: '198ms',
        p95Latency: '365ms',
        errorRate: '0.52%',
        timeoutRate: '0.12%',
        requestsPerMin: '41 rpm',
        retryRate: '2.1%',
        availability: '99.90%',
        lastIncident: 'None · 6d',
        operationalStatus: 'Healthy',
        severityLabel: 'OK',
        insight: 'Owner resolution for routing escalations.',
        latencySparkline: sp(40, 41, 40, 42, 41, 40, 41, 40, 41, 40),
      },
    ],
  },
  servicenow: {
    summary: 'Sensitive to auth token lifecycle and regional instance load.',
    operationalNotes: ['Proactive token refresh', 'Monitor table API p95'],
    agentToolingContext:
      'ITSM agents create and update incidents, query CMDB snippets, and attach knowledge articles during agent-assisted tickets.',
    dependencyOverview: {
      productionAgentCount: 3,
      workflowCount: 7,
      criticality: 'High',
      fallbackEnabled: false,
      volumeClass: 'Medium',
      primaryWorkflows: ['ITSM Agent', 'SRE Copilot', 'Internal FAQ'],
      agentNames: ['ITSM Agent', 'SRE Copilot', 'Internal FAQ'],
      notes: ['Auth token expiry drives periodic agent tool failures without refresh.'],
    },
    runtimeBreakdown: {
      network: '33%',
      processing: '40%',
      authOverhead: '15%',
      retryOverhead: '9%',
      fallbackExecution: '3%',
    },
    timeline: [
      { timeUtc: '07:50 UTC', message: 'OAuth token refresh storm — ITSM Agent degraded', tone: 'critical' },
      { timeUtc: '08:04 UTC', message: 'Proactive refresh policy deployed', tone: 'positive' },
    ],
    endpoints: [
      {
        path: '/api/now/table/incident',
        avgLatency: '352ms',
        p95Latency: '690ms',
        errorRate: '1.35%',
        timeoutRate: '0.48%',
        requestsPerMin: '112 rpm',
        retryRate: '4.2%',
        availability: '99.71%',
        lastIncident: 'Auth · 4h ago',
        operationalStatus: 'Degraded',
        severityLabel: 'Watch',
        insight: 'Table API p95 tracks instance load; auth overhead visible in traces.',
        latencySparkline: sp(52, 54, 56, 60, 62, 60, 58, 56, 55, 54),
      },
      {
        path: '/api/now/table/sys_user',
        avgLatency: '298ms',
        p95Latency: '560ms',
        errorRate: '1.02%',
        timeoutRate: '0.35%',
        requestsPerMin: '64 rpm',
        retryRate: '3.5%',
        availability: '99.76%',
        lastIncident: 'Timeout · 1d ago',
        operationalStatus: 'Healthy',
        severityLabel: 'Watch',
        insight: 'User resolution for assignment groups in ITSM Agent.',
        latencySparkline: sp(48, 50, 51, 53, 52, 50, 49, 48, 49, 48),
      },
      {
        path: '/api/now/kb/knowledge',
        avgLatency: '318ms',
        p95Latency: '605ms',
        errorRate: '1.12%',
        timeoutRate: '0.38%',
        requestsPerMin: '48 rpm',
        retryRate: '3.8%',
        availability: '99.74%',
        lastIncident: 'None · 2d',
        operationalStatus: 'Healthy',
        severityLabel: 'Watch',
        insight: 'Knowledge retrieval for suggested resolutions.',
        latencySparkline: sp(50, 52, 53, 55, 54, 52, 51, 50, 51, 50),
      },
      {
        path: '/api/now/stats/incident',
        avgLatency: '275ms',
        p95Latency: '515ms',
        errorRate: '0.88%',
        timeoutRate: '0.28%',
        requestsPerMin: '36 rpm',
        retryRate: '3.1%',
        availability: '99.80%',
        lastIncident: 'None · 5d',
        operationalStatus: 'Healthy',
        severityLabel: 'OK',
        insight: 'Aggregate reads for management-facing agent summaries.',
        latencySparkline: sp(46, 47, 48, 49, 48, 47, 46, 47, 46, 47),
      },
    ],
  },
  confluence: {
    summary: 'Predictable for CQL-scoped page fetch.',
    operationalNotes: ['Limit page tree depth in automation'],
    agentToolingContext:
      'Internal support and onboarding agents retrieve runbooks and policy pages with bounded CQL queries.',
    dependencyOverview: {
      productionAgentCount: 4,
      workflowCount: 6,
      criticality: 'Standard',
      fallbackEnabled: true,
      volumeClass: 'Low',
      primaryWorkflows: ['Internal FAQ', 'Onboarding Guide', 'SRE Copilot', 'Compliance Helper'],
      agentNames: ['Internal FAQ', 'Onboarding Guide', 'SRE Copilot', 'Compliance Helper'],
      notes: ['Fallback to cached HTML snapshots when search degrades.'],
    },
    runtimeBreakdown: {
      network: '34%',
      processing: '43%',
      authOverhead: '12%',
      retryOverhead: '8%',
      fallbackExecution: '3%',
    },
    timeline: [
      { timeUtc: '18:10 UTC', message: 'CQL search latency elevated — depth limit enforced', tone: 'warning' },
      { timeUtc: '18:22 UTC', message: 'Recovery — agent cache hit rate improved', tone: 'positive' },
    ],
    endpoints: [
      {
        path: '/wiki/rest/api/content/search',
        avgLatency: '305ms',
        p95Latency: '575ms',
        errorRate: '0.62%',
        timeoutRate: '0.22%',
        requestsPerMin: '86 rpm',
        retryRate: '2.5%',
        availability: '99.89%',
        lastIncident: 'Search · 2d ago',
        operationalStatus: 'Healthy',
        severityLabel: 'OK',
        insight: 'CQL scope limits prevent runaway agent retrieval.',
        latencySparkline: sp(47, 49, 50, 52, 51, 49, 48, 47, 48, 47),
      },
      {
        path: '/wiki/rest/api/content',
        avgLatency: '278ms',
        p95Latency: '525ms',
        errorRate: '0.55%',
        timeoutRate: '0.18%',
        requestsPerMin: '102 rpm',
        retryRate: '2.2%',
        availability: '99.91%',
        lastIncident: 'None · 4d',
        operationalStatus: 'Healthy',
        severityLabel: 'OK',
        insight: 'Page body fetch for runbook grounding.',
        latencySparkline: sp(45, 46, 47, 48, 47, 46, 45, 46, 45, 46),
      },
      {
        path: '/wiki/rest/api/space',
        avgLatency: '242ms',
        p95Latency: '455ms',
        errorRate: '0.48%',
        timeoutRate: '0.14%',
        requestsPerMin: '34 rpm',
        retryRate: '1.9%',
        availability: '99.93%',
        lastIncident: 'None · 7d',
        operationalStatus: 'Healthy',
        severityLabel: 'OK',
        insight: 'Space metadata for scoping agent searches.',
        latencySparkline: sp(42, 43, 42, 44, 43, 42, 43, 42, 43, 42),
      },
      {
        path: '/wiki/rest/api/user/current',
        avgLatency: '198ms',
        p95Latency: '375ms',
        errorRate: '0.42%',
        timeoutRate: '0.10%',
        requestsPerMin: '28 rpm',
        retryRate: '1.6%',
        availability: '99.94%',
        lastIncident: 'None · 8d',
        operationalStatus: 'Healthy',
        severityLabel: 'OK',
        insight: 'Lightweight auth context check for agent sessions.',
        latencySparkline: sp(38, 39, 38, 40, 39, 38, 39, 38, 39, 38),
      },
    ],
  },
  notion: {
    summary: 'Good for structured blocks; rate limits on bulk sync.',
    operationalNotes: ['Throttle block updates during reindex'],
    agentToolingContext:
      'Playbook and CS agents sync structured blocks and query databases for procedural knowledge.',
    dependencyOverview: {
      productionAgentCount: 3,
      workflowCount: 5,
      criticality: 'Standard',
      fallbackEnabled: true,
      volumeClass: 'Medium',
      primaryWorkflows: ['Playbook Agent', 'Support Assistant', 'Onboarding Guide'],
      agentNames: ['Playbook Agent', 'Support Assistant', 'Onboarding Guide'],
      notes: ['Bulk sync tools share rate limits — coordinator serializes writes.'],
    },
    runtimeBreakdown: {
      network: '31%',
      processing: '42%',
      authOverhead: '9%',
      retryOverhead: '13%',
      fallbackExecution: '5%',
    },
    timeline: [
      { timeUtc: '20:05 UTC', message: 'Block update throttle — reindex in progress', tone: 'warning' },
      { timeUtc: '20:28 UTC', message: 'Sync coordinator cleared backlog', tone: 'positive' },
    ],
    endpoints: [
      {
        path: '/v1/pages/{id}',
        avgLatency: '312ms',
        p95Latency: '595ms',
        errorRate: '0.88%',
        timeoutRate: '0.28%',
        requestsPerMin: '74 rpm',
        retryRate: '3.4%',
        availability: '99.83%',
        lastIncident: 'Rate limit · 6h ago',
        operationalStatus: 'Healthy',
        severityLabel: 'Watch',
        insight: 'Page fetches for playbook grounding — watch nested blocks.',
        latencySparkline: sp(48, 50, 52, 54, 53, 51, 49, 48, 49, 48),
      },
      {
        path: '/v1/blocks/{id}/children',
        avgLatency: '335ms',
        p95Latency: '640ms',
        errorRate: '0.95%',
        timeoutRate: '0.32%',
        requestsPerMin: '58 rpm',
        retryRate: '3.8%',
        availability: '99.81%',
        lastIncident: 'Throttle · 6h ago',
        operationalStatus: 'Degraded',
        severityLabel: 'Watch',
        insight: 'Block children walks drive bulk sync cost for Playbook Agent.',
        latencySparkline: sp(50, 52, 55, 58, 60, 57, 55, 53, 52, 51),
      },
      {
        path: '/v1/databases/query',
        avgLatency: '298ms',
        p95Latency: '555ms',
        errorRate: '0.78%',
        timeoutRate: '0.24%',
        requestsPerMin: '66 rpm',
        retryRate: '3.0%',
        availability: '99.85%',
        lastIncident: 'None · 1d',
        operationalStatus: 'Healthy',
        severityLabel: 'OK',
        insight: 'Database queries for structured FAQ rows.',
        latencySparkline: sp(46, 48, 49, 51, 50, 48, 47, 46, 47, 46),
      },
      {
        path: '/v1/search',
        avgLatency: '288ms',
        p95Latency: '535ms',
        errorRate: '0.72%',
        timeoutRate: '0.22%',
        requestsPerMin: '52 rpm',
        retryRate: '2.9%',
        availability: '99.86%',
        lastIncident: 'None · 2d',
        operationalStatus: 'Healthy',
        severityLabel: 'OK',
        insight: 'Workspace-wide search — agents use narrow filters.',
        latencySparkline: sp(45, 46, 47, 48, 47, 46, 45, 46, 45, 46),
      },
    ],
  },
  'google-calendar': {
    summary: 'Stable with quota-aware batching.',
    operationalNotes: ['Prefer incremental sync tokens'],
    agentToolingContext:
      'Scheduling agents list events, create holds, and query free/busy for handoff meetings and customer calls.',
    dependencyOverview: {
      productionAgentCount: 4,
      workflowCount: 10,
      criticality: 'High',
      fallbackEnabled: true,
      volumeClass: 'Medium',
      primaryWorkflows: ['Scheduling Agent', 'Sales Copilot', 'Support Assistant', 'Onboarding Guide'],
      agentNames: ['Scheduling Agent', 'Sales Copilot', 'Support Assistant', 'Onboarding Guide'],
      notes: ['Fallback suggests alternate slots when free/busy errors spike.'],
    },
    runtimeBreakdown: {
      network: '26%',
      processing: '48%',
      authOverhead: '14%',
      retryOverhead: '9%',
      fallbackExecution: '3%',
    },
    timeline: [
      { timeUtc: '10:15 UTC', message: 'Quota warning — batch size reduced for agent calendar tools', tone: 'warning' },
      { timeUtc: '10:30 UTC', message: 'freebusy/query latency normalized', tone: 'positive' },
    ],
    endpoints: [
      {
        path: '/calendar/v3/events/list',
        avgLatency: '218ms',
        p95Latency: '405ms',
        errorRate: '0.38%',
        timeoutRate: '0.11%',
        requestsPerMin: '186 rpm',
        retryRate: '1.6%',
        availability: '99.93%',
        lastIncident: 'Quota · 1d ago',
        operationalStatus: 'Healthy',
        severityLabel: 'OK',
        insight: 'Event list drives agent scheduling context windows.',
        latencySparkline: sp(42, 43, 44, 45, 44, 43, 42, 43, 42, 43),
      },
      {
        path: '/calendar/v3/events/insert',
        avgLatency: '232ms',
        p95Latency: '430ms',
        errorRate: '0.42%',
        timeoutRate: '0.13%',
        requestsPerMin: '74 rpm',
        retryRate: '1.7%',
        availability: '99.92%',
        lastIncident: 'None · 3d',
        operationalStatus: 'Healthy',
        severityLabel: 'OK',
        insight: 'Creates customer-facing holds from Scheduling Agent.',
        latencySparkline: sp(43, 44, 45, 46, 45, 44, 43, 44, 43, 44),
      },
      {
        path: '/calendar/v3/freebusy/query',
        avgLatency: '198ms',
        p95Latency: '375ms',
        errorRate: '0.32%',
        timeoutRate: '0.09%',
        requestsPerMin: '142 rpm',
        retryRate: '1.4%',
        availability: '99.94%',
        lastIncident: 'Spike · 8h ago',
        operationalStatus: 'Healthy',
        severityLabel: 'OK',
        insight: 'Hot path for slot suggestion — sensitive to concurrent agent calls.',
        latencySparkline: sp(40, 41, 42, 44, 43, 41, 40, 39, 40, 39),
      },
      {
        path: '/calendar/v3/calendars/get',
        avgLatency: '175ms',
        p95Latency: '328ms',
        errorRate: '0.28%',
        timeoutRate: '0.07%',
        requestsPerMin: '58 rpm',
        retryRate: '1.2%',
        availability: '99.95%',
        lastIncident: 'None · 6d',
        operationalStatus: 'Healthy',
        severityLabel: 'OK',
        insight: 'Calendar metadata validation before writes.',
        latencySparkline: sp(38, 39, 38, 40, 39, 38, 39, 38, 39, 38),
      },
    ],
  },
  'internal-crm': {
    summary: 'Low average latency with retry amplification risk.',
    operationalNotes: ['Check replica lag', 'Circuit-break noisy endpoints'],
    agentToolingContext:
      'First-party CRM tools power customer profile, shipment status, account lookup, and case history for multiple agent fleets.',
    dependencyOverview: {
      productionAgentCount: 7,
      workflowCount: 16,
      criticality: 'Critical',
      fallbackEnabled: true,
      volumeClass: 'High-volume',
      primaryWorkflows: [
        'Support Assistant — profile & case history',
        'Logistics Agent — shipment status',
        'Sales Copilot — account lookup',
      ],
      agentNames: [
        'Support Assistant',
        'Logistics Agent',
        'Sales Copilot',
        'Billing Agent',
        'Onboarding Guide',
        'Escalation Router',
        'Internal FAQ',
      ],
      notes: [
        'Used by 7 production agents — highest internal dependency fan-out.',
        'Fallback enabled to stale read store when primary errors spike.',
      ],
    },
    runtimeBreakdown: {
      network: '24%',
      processing: '39%',
      authOverhead: '8%',
      retryOverhead: '22%',
      fallbackExecution: '7%',
    },
    timeline: [
      { timeUtc: '13:05 UTC', message: 'Replica lag detected — /customer/profile reads stale', tone: 'warning' },
      { timeUtc: '13:18 UTC', message: 'Schema mismatch detected for /customer/profile — contract test failed', tone: 'critical' },
      { timeUtc: '13:40 UTC', message: 'Fallback reads engaged — error budget stabilizing', tone: 'neutral' },
    ],
    endpoints: [
      {
        path: '/customer/profile',
        avgLatency: '198ms',
        p95Latency: '455ms',
        errorRate: '1.85%',
        timeoutRate: '0.62%',
        requestsPerMin: '512 rpm',
        retryRate: '6.8%',
        availability: '99.58%',
        lastIncident: 'Schema · 4h ago',
        operationalStatus: 'Critical',
        severityLabel: 'Elevated',
        insight: 'Schema mismatch detected for /customer/profile — field map out of sync with agent tool contract.',
        latencySparkline: sp(45, 48, 52, 58, 62, 60, 56, 54, 52, 50),
      },
      {
        path: '/shipment/status',
        avgLatency: '172ms',
        p95Latency: '398ms',
        errorRate: '1.42%',
        timeoutRate: '0.48%',
        requestsPerMin: '284 rpm',
        retryRate: '5.4%',
        availability: '99.64%',
        lastIncident: 'Retry storm · 1d ago',
        operationalStatus: 'Degraded',
        severityLabel: 'Watch',
        insight: 'Logistics Agent polls heavily during carrier outages.',
        latencySparkline: sp(42, 44, 46, 50, 52, 50, 48, 46, 45, 44),
      },
      {
        path: '/account/lookup',
        avgLatency: '158ms',
        p95Latency: '360ms',
        errorRate: '1.18%',
        timeoutRate: '0.38%',
        requestsPerMin: '368 rpm',
        retryRate: '4.9%',
        availability: '99.70%',
        lastIncident: 'Lag · 6h ago',
        operationalStatus: 'Degraded',
        severityLabel: 'Watch',
        insight: 'Account resolution for Sales Copilot — replica lag sensitive.',
        latencySparkline: sp(40, 42, 44, 46, 45, 43, 42, 41, 40, 41),
      },
      {
        path: '/case/history',
        avgLatency: '205ms',
        p95Latency: '480ms',
        errorRate: '1.55%',
        timeoutRate: '0.55%',
        requestsPerMin: '196 rpm',
        retryRate: '5.9%',
        availability: '99.62%',
        lastIncident: 'Timeout · 2d ago',
        operationalStatus: 'Degraded',
        severityLabel: 'Elevated',
        insight: 'Long histories stress agent context assembly — pagination caps applied.',
        latencySparkline: sp(44, 46, 48, 52, 54, 52, 50, 48, 47, 46),
      },
    ],
  },
  'delivery-tracking': {
    summary: 'Schema and timeout sensitive; critical for logistics agents.',
    operationalNotes: ['Contract tests on payload shape', 'Fallback carrier routing'],
    agentToolingContext:
      'Logistics and support agents track shipments, ETAs, and exception events for order status inquiries.',
    dependencyOverview: {
      productionAgentCount: 3,
      workflowCount: 6,
      criticality: 'Critical',
      fallbackEnabled: true,
      volumeClass: 'Medium',
      primaryWorkflows: ['Logistics Agent', 'Support Assistant', 'Onboarding Guide'],
      agentNames: ['Logistics Agent', 'Support Assistant', 'Onboarding Guide'],
      notes: ['Fallback carrier routing when primary logistics partner errors exceed budget.'],
    },
    runtimeBreakdown: {
      network: '41%',
      processing: '35%',
      authOverhead: '7%',
      retryOverhead: '14%',
      fallbackExecution: '3%',
    },
    timeline: [
      { timeUtc: '05:30 UTC', message: 'Carrier partner timeout spike — Logistics Agent degraded', tone: 'critical' },
      { timeUtc: '05:48 UTC', message: 'Fallback routing engaged', tone: 'warning' },
      { timeUtc: '06:05 UTC', message: 'Primary path recovered', tone: 'positive' },
    ],
    endpoints: [
      {
        path: '/v1/shipments/{id}',
        avgLatency: '398ms',
        p95Latency: '820ms',
        errorRate: '1.72%',
        timeoutRate: '0.88%',
        requestsPerMin: '142 rpm',
        retryRate: '7.2%',
        availability: '99.55%',
        lastIncident: 'Timeout · 5h ago',
        operationalStatus: 'Degraded',
        severityLabel: 'Elevated',
        insight: 'Primary tracking read — carrier latency dominates p95.',
        latencySparkline: sp(55, 58, 62, 68, 72, 70, 65, 62, 60, 58),
      },
      {
        path: '/v1/shipments/eta',
        avgLatency: '365ms',
        p95Latency: '760ms',
        errorRate: '1.58%',
        timeoutRate: '0.76%',
        requestsPerMin: '98 rpm',
        retryRate: '6.6%',
        availability: '99.58%',
        lastIncident: 'Schema · 2d ago',
        operationalStatus: 'Degraded',
        severityLabel: 'Watch',
        insight: 'ETA field occasionally null — agent prompts user for manual verify.',
        latencySparkline: sp(52, 55, 58, 62, 64, 62, 58, 56, 54, 53),
      },
      {
        path: '/v1/tracking/events',
        avgLatency: '342ms',
        p95Latency: '705ms',
        errorRate: '1.48%',
        timeoutRate: '0.68%',
        requestsPerMin: '76 rpm',
        retryRate: '6.2%',
        availability: '99.60%',
        lastIncident: 'None · 8h',
        operationalStatus: 'Healthy',
        severityLabel: 'Watch',
        insight: 'Event stream for milestone narration in agent replies.',
        latencySparkline: sp(50, 52, 54, 56, 55, 53, 51, 50, 51, 50),
      },
      {
        path: '/v1/carriers/resolve',
        avgLatency: '288ms',
        p95Latency: '590ms',
        errorRate: '1.22%',
        timeoutRate: '0.45%',
        requestsPerMin: '34 rpm',
        retryRate: '5.1%',
        availability: '99.68%',
        lastIncident: 'None · 1d',
        operationalStatus: 'Healthy',
        severityLabel: 'OK',
        insight: 'Maps tracking IDs to carrier endpoints for tool routing.',
        latencySparkline: sp(46, 47, 48, 50, 49, 47, 46, 45, 46, 45),
      },
    ],
  },
  'identity-auth': {
    summary: 'Foundational dependency — small failures cascade quickly.',
    operationalNotes: ['Alert on auth error rate spikes', 'Regional clock skew checks'],
    agentToolingContext:
      'Every agent tool invocation validates tokens via IAM — failures block downstream CRM, ticketing, and payment calls.',
    dependencyOverview: {
      productionAgentCount: 12,
      workflowCount: 28,
      criticality: 'Critical',
      fallbackEnabled: false,
      volumeClass: 'High-volume',
      primaryWorkflows: ['All production agents — pre-tool auth gate'],
      agentNames: [
        'Fleet-wide',
        'Support Assistant',
        'Sales Copilot',
        'Billing Agent',
        'Scheduling Agent',
        'Logistics Agent',
        '… +7 more',
      ],
      notes: [
        'Impacts multiple agents — single auth outage stalls tool execution across workflows.',
        'No fallback — strict security posture; agents surface auth errors to users.',
      ],
    },
    runtimeBreakdown: {
      network: '18%',
      processing: '28%',
      authOverhead: '48%',
      retryOverhead: '4%',
      fallbackExecution: '2%',
    },
    timeline: [
      { timeUtc: '08:55 UTC', message: 'Auth error rate spike — regional clock skew suspected', tone: 'critical' },
      { timeUtc: '09:08 UTC', message: 'NTP drift corrected — introspect latency normalized', tone: 'positive' },
    ],
    endpoints: [
      {
        path: '/oauth2/token',
        avgLatency: '88ms',
        p95Latency: '165ms',
        errorRate: '0.12%',
        timeoutRate: '0.03%',
        requestsPerMin: '420 rpm',
        retryRate: '0.35%',
        availability: '99.98%',
        lastIncident: 'Skew · 6h ago',
        operationalStatus: 'Healthy',
        severityLabel: 'OK',
        insight: 'Token issuance hot path — monitored for agent burst logins.',
        latencySparkline: sp(30, 31, 30, 32, 31, 30, 31, 30, 31, 30),
      },
      {
        path: '/v1/token/introspect',
        avgLatency: '72ms',
        p95Latency: '142ms',
        errorRate: '0.10%',
        timeoutRate: '0.02%',
        requestsPerMin: '1850 rpm',
        retryRate: '0.28%',
        availability: '99.99%',
        lastIncident: 'None · 10d',
        operationalStatus: 'Healthy',
        severityLabel: 'OK',
        insight: 'Highest RPM — every tool call hits introspection.',
        latencySparkline: sp(28, 29, 28, 30, 29, 28, 29, 28, 29, 28),
      },
      {
        path: '/v1/sessions/validate',
        avgLatency: '95ms',
        p95Latency: '178ms',
        errorRate: '0.14%',
        timeoutRate: '0.04%',
        requestsPerMin: '620 rpm',
        retryRate: '0.38%',
        availability: '99.97%',
        lastIncident: 'None · 7d',
        operationalStatus: 'Healthy',
        severityLabel: 'OK',
        insight: 'Session continuity for long-running agent threads.',
        latencySparkline: sp(32, 33, 32, 34, 33, 32, 33, 32, 33, 32),
      },
      {
        path: '/v1/policies/evaluate',
        avgLatency: '102ms',
        p95Latency: '195ms',
        errorRate: '0.16%',
        timeoutRate: '0.05%',
        requestsPerMin: '290 rpm',
        retryRate: '0.42%',
        availability: '99.96%',
        lastIncident: 'None · 5d',
        operationalStatus: 'Healthy',
        severityLabel: 'OK',
        insight: 'Fine-grained policy for sensitive tool routes (payments, PII).',
        latencySparkline: sp(33, 34, 35, 36, 35, 34, 33, 34, 33, 34),
      },
    ],
  },
}
